// Component
export { SimpleTableComponent } from "./lib/SimpleTableComponent";
export { asRows } from "simple-table-core";

// Provider helper
export { provideSimpleTable } from "./lib/provideSimpleTable";

/** Wrap a standalone component as an HTMLElement (e.g. for `tableEmptyStateRenderer`). */
export { wrapAngularRenderer } from "./utils/wrapAngularRenderer";

// Angular-specific props and type overrides
export type {
  SimpleTableAngularProps,
  TableInstance,
  AngularHeaderObject,
  AngularIconsConfig,
  AngularIconSlot,
  AngularColumnEditorConfig,
  AngularCellRenderer,
  AngularHeaderRenderer,
  AngularFooterRenderer,
  AngularHeaderDropdown,
  AngularColumnEditorRowRenderer,
  AngularColumnEditorCustomRenderer,
  AngularLoadingStateRenderer,
  AngularErrorStateRenderer,
  AngularEmptyStateRenderer,
} from "./types";

// Re-export vanilla types consumers need when building column definitions,
// callbacks, or using the imperative API via @ViewChild / (tableReady) output.
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  BoundingBox,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorRowRendererComponents,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorRowRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  DragHandlerProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FooterRendererProps,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderDropdownProps,
  HeaderObject,
  HeaderRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  OnSortProps,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowState,
  SetHeaderRenameProps,
  SharedTableProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  TableAPI,
  TableFilterState,
  TableHeaderProps,
  TableRowProps,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";
