// Component
export { default as SimpleTable } from "./SimpleTable";
export { asRows } from "simple-table-core";

// React-specific props and type overrides
export type {
  SimpleTableReactProps,
  TableInstance,
  ReactHeaderObject,
  ReactColumnEditorConfig,
  ReactIconsConfig,
  ReactIconElement,
  ReactCellRenderer,
  ReactHeaderRenderer,
  ReactFooterRenderer,
  ReactHeaderDropdown,
  ReactColumnEditorRowRenderer,
  ReactColumnEditorCustomRenderer,
  ReactLoadingStateRenderer,
  ReactErrorStateRenderer,
  ReactEmptyStateRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  ColumnEditorRowRendererComponents,
  ColumnEditorRowRendererProps,
  FooterRendererProps,
  HeaderDropdownProps,
} from "./types";

// Re-export vanilla types for callbacks and the imperative ref API. For
// column definitions and column-related callbacks on `SimpleTable`, use
// `ReactHeaderObject` (exported above).
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  BoundingBox,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  DragHandlerProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderRenderer,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  OnSortProps,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowState,
  SetHeaderRenameProps,
  SharedTableProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  // TableAPI is the type consumers use for useRef<TableAPI>(null)
  TableAPI,
  TableFilterState,
  TableHeaderProps,
  TableRowProps,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";
