export const DEMO_LIST = [
  { id: "quick-start", label: "Quick Start" },
  { id: "column-filtering", label: "Column Filtering" },
  { id: "column-sorting", label: "Column Sorting" },
  { id: "value-formatter", label: "Value Formatter" },
  { id: "pagination", label: "Pagination" },
  { id: "column-pinning", label: "Column Pinning" },
  { id: "column-alignment", label: "Column Alignment" },
  { id: "column-width", label: "Column Width" },
  { id: "column-resizing", label: "Column Resizing" },
  { id: "column-reordering", label: "Column Reordering" },
  { id: "column-selection", label: "Column Selection" },
  { id: "column-editing", label: "Column Editing" },
  { id: "cell-editing", label: "Cell Editing" },
  { id: "cell-highlighting", label: "Cell Highlighting" },
  { id: "themes", label: "Themes" },
  { id: "row-height", label: "Row Height" },
  { id: "table-height", label: "Table Height" },
  { id: "quick-filter", label: "Quick Filter" },
  { id: "nested-headers", label: "Nested Headers" },
  { id: "external-sort", label: "External Sort" },
  { id: "external-filter", label: "External Filter" },
  { id: "loading-state", label: "Loading State" },
  { id: "infinite-scroll", label: "Infinite Scroll" },
  { id: "window-infinite-scroll", label: "Window Infinite Scroll" },
  { id: "row-selection", label: "Row Selection" },
  { id: "csv-export", label: "CSV Export" },
  { id: "programmatic-control", label: "Programmatic Control" },
  { id: "row-grouping", label: "Row Grouping" },
  { id: "aggregate-functions", label: "Aggregate Functions" },
  { id: "collapsible-columns", label: "Collapsible Columns" },
  { id: "cell-renderer", label: "Cell Renderer" },
  { id: "header-renderer", label: "Header Renderer" },
  { id: "footer-renderer", label: "Footer Renderer" },
  { id: "cell-clicking", label: "Cell Clicking" },
  { id: "tooltip", label: "Tooltip" },
  { id: "custom-theme", label: "Custom Theme" },
  { id: "custom-icons", label: "Custom Icons" },
  { id: "empty-state", label: "Empty State" },
  { id: "column-visibility", label: "Column Visibility" },
  { id: "column-editor-custom-renderer", label: "Column Editor Custom Renderer" },
  { id: "single-row-children", label: "Single Row Children" },
  { id: "nested-tables", label: "Nested Tables" },
  { id: "dynamic-nested-tables", label: "Dynamic Nested Tables" },
  { id: "dynamic-row-loading", label: "Dynamic Row Loading" },
  { id: "charts", label: "Charts" },
  { id: "live-update", label: "Live Update" },
  { id: "crm", label: "CRM" },
  { id: "infrastructure", label: "Infrastructure" },
  { id: "music", label: "Music" },
  { id: "billing", label: "Billing" },
  { id: "manufacturing", label: "Manufacturing" },
  { id: "hr", label: "HR" },
  { id: "sales", label: "Sales" },
] as const;

export type DemoId = (typeof DEMO_LIST)[number]["id"];
